# SwiftLint Configuration for GitPeek
# Based on Apple's API Design Guidelines and industry best practices

# パスの設定
included:
  - GitPeek
  - GitPeekTests
  - GitPeekUITests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - ${PWD}/.build
  - ${PWD}/Carthage
  - ${PWD}/Pods

# アナライザールール（より深い解析）
analyzer_rules:
  - unused_declaration
  - unused_import
  - capture_variable
  - typesafe_array_init

# オプトインルール（強力な品質チェック）
opt_in_rules:
  # パフォーマンス
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last
  
  # 正確性
  - array_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - lower_acl_than_parent
  - overridden_super_call
  - prohibited_super_call
  - redundant_type_annotation
  - unowned_variable_capture
  - weak_delegate
  
  # スタイル
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - convenience_type
  - empty_enum_arguments
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  
  # 命名規則
  - enum_case_associated_values_count
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - file_name
  - file_name_no_space
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_whitespace
  - optional_enum_case_matching
  - prefer_self_in_static_references
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - static_operator
  - toggle_bool
  - unavailable_function
  - untyped_error_in_catch
  
  # ドキュメント
  - documentation_in_extensions
  - multiline_arguments_brackets
  - multiline_parameters_brackets

# 無効化するルール
disabled_rules:
  - todo # TODOコメントは開発中は許可
  - line_length # 下記でカスタマイズ
  - file_length # 下記でカスタマイズ

# カスタムルール
custom_rules:
  no_print_statements:
    name: "Print Statements"
    message: "Print statements should not be used in production code. Use proper logging instead."
    regex: '^\s*print\('
    match_kinds:
      - identifier
    severity: warning
    
  no_force_cast:
    name: "Force Cast"
    message: "Force casts should be avoided."
    regex: 'as! '
    severity: error
    
  no_force_try:
    name: "Force Try"
    message: "Force tries should be avoided."
    regex: 'try!'
    severity: error
    
  space_after_main_type:
    name: "Space After Main Type"
    message: "Add a blank line after the main type declaration."
    regex: '(class|struct|enum|protocol) [A-Z]\w+.*\{\n[^\n]'
    severity: warning
    
  marks_format:
    name: "MARK Format"
    message: "MARK comments should follow the format: // MARK: - Description"
    regex: '\/\/\s*MARK:[^-]|\/\/\s*MARK:\s*-[^ ]'
    severity: warning

# ルール設定
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true
  excluded:
    - id
    - URL
    - url
    - x
    - y
    - z
    - i
    - j
    - k

nesting:
  type_level: 2
  function_level: 3

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

# Appleの命名規則に準拠
# - クラリティが最優先
# - 簡潔性より明確性
# - 使用時の文脈で明確であること

colon:
  apply_to_dictionaries: true
  flexible_right_spacing: false

# 強制アンラップの報告
force_cast: error
force_unwrapping: error

# インデント
indentation_width:
  indentation_width: 4
  include_comments: false

# Swift 5.9+ の機能を活用
deployment_target:
  iOS_deployment_target: 17.0
  macOS_deployment_target: 13.0

# レポート出力
reporter: "xcode" # Xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging